// Weapon defs (emoji = canvas sprite). `behavior` drives WeaponSystem firing.
// Base numbers are pre-stat; scaleWeapon(def, level) applies level scaling, then the
// system multiplies by resolved stats (might/area/cooldown/projSpeed/projCount...).
// Each base weapon evolves at L8 while holding `requiresPassive`.
//
// behaviors: aimed · spread · whip · aura · lob · orbit · nova
export const WEAPONS = {
  whip: {
    id: "whip",
    name: "Whip",
    emoji: "〰️",
    behavior: "whip",
    damage: 16,
    cooldown: 1.0,
    count: 1,
    pierce: 999,
    area: 1,
    range: 140,
    arc: 1.4,
    countEvery: 3,
    evolvesTo: "bloodletter",
    requiresPassive: "hollowHeart",
  },
  bolt: {
    id: "bolt",
    name: "Magic Bolt",
    emoji: "🔵",
    behavior: "aimed",
    damage: 12,
    cooldown: 0.85,
    count: 1,
    pierce: 2,
    area: 1,
    speed: 460,
    countEvery: 3,
    evolvesTo: "boltStorm",
    requiresPassive: "spellFocus",
  },
  daggers: {
    id: "daggers",
    name: "Daggers",
    emoji: "🔪",
    behavior: "spread",
    damage: 9,
    cooldown: 0.62,
    count: 3,
    pierce: 1,
    area: 1,
    speed: 540,
    spread: 0.5,
    countEvery: 2,
    evolvesTo: "fanOfKnives",
    requiresPassive: "bracer",
  },
  aura: {
    id: "aura",
    name: "Thorn Aura",
    emoji: "🌀",
    behavior: "aura",
    damage: 7,
    cooldown: 0.5,
    count: 1,
    pierce: 999,
    area: 1,
    radius: 94,
    color: "rgba(116,224,74,",
    evolvesTo: "infernoRing",
    requiresPassive: "waxCandle",
  },
  axe: {
    id: "axe",
    name: "Axe",
    emoji: "🪓",
    behavior: "lob",
    damage: 26,
    cooldown: 1.3,
    count: 1,
    pierce: 999,
    area: 1,
    speed: 360,
    lobTime: 0.5,
    splash: 72,
    countEvery: 3,
    color: "rgba(232,193,74,",
    evolvesTo: "meteor",
    requiresPassive: "spinach",
  },
  orbit: {
    id: "orbit",
    name: "Orbit Orbs",
    emoji: "🔆",
    behavior: "orbit",
    damage: 11,
    cooldown: 0,
    count: 2,
    pierce: 999,
    area: 1,
    radius: 82,
    orbitSpeed: 2.8,
    hitCd: 0.3,
    size: 22,
    countEvery: 2,
    evolvesTo: "halo",
    requiresPassive: "echoStone",
  },

  // ── Evolutions (granted, not offered as new weapons) ──
  bloodletter: {
    id: "bloodletter",
    name: "Bloodletter",
    emoji: "🩸",
    behavior: "whip",
    evolved: true,
    damage: 24,
    cooldown: 0.95,
    count: 2,
    pierce: 999,
    area: 1.3,
    range: 150,
    arc: 1.3,
    lifesteal: 0.06,
    countEvery: 3,
  },
  boltStorm: {
    id: "boltStorm",
    name: "Bolt Storm",
    emoji: "🌩️",
    behavior: "nova",
    evolved: true,
    damage: 17,
    cooldown: 0.9,
    count: 9,
    pierce: 2,
    area: 1,
    speed: 460,
    countEvery: 4,
    countStep: 2,
  },
  fanOfKnives: {
    id: "fanOfKnives",
    name: "Fan of Knives",
    emoji: "🌪️",
    behavior: "spread",
    evolved: true,
    damage: 13,
    cooldown: 0.5,
    count: 6,
    pierce: 2,
    area: 1,
    speed: 560,
    spread: 0.95,
    countEvery: 2,
  },
  infernoRing: {
    id: "infernoRing",
    name: "Inferno Ring",
    emoji: "🔥",
    behavior: "aura",
    evolved: true,
    damage: 12,
    cooldown: 0.45,
    count: 1,
    pierce: 999,
    area: 1.5,
    radius: 86,
    color: "rgba(255,120,40,",
  },
  meteor: {
    id: "meteor",
    name: "Meteor",
    emoji: "☄️",
    behavior: "lob",
    evolved: true,
    damage: 44,
    cooldown: 1.3,
    count: 1,
    pierce: 999,
    area: 1.8,
    speed: 340,
    lobTime: 0.6,
    splash: 78,
    countEvery: 3,
    color: "rgba(255,90,40,",
  },
  halo: {
    id: "halo",
    name: "Halo",
    emoji: "💫",
    behavior: "orbit",
    evolved: true,
    damage: 16,
    cooldown: 0,
    count: 4,
    pierce: 999,
    area: 1.4,
    radius: 92,
    orbitSpeed: 3.2,
    hitCd: 0.28,
    size: 24,
  },
};

export const WEAPON_IDS = Object.keys(WEAPONS);
// New-weapon pool offered at level-up (base, non-evolved only).
export const BASE_WEAPON_IDS = WEAPON_IDS.filter((id) => !WEAPONS[id].evolved);
export const MAX_WEAPON_LEVEL = 8;

// Level scaling (pre-stat). count grows every `countEvery` levels by `countStep`.
export function scaleWeapon(def, level) {
  const l = level - 1;
  return {
    damage: def.damage * (1 + 0.26 * l),
    interval: def.cooldown * Math.pow(0.95, l),
    count:
      def.count + Math.floor(l / (def.countEvery || 3)) * (def.countStep || 1),
    pierce: def.pierce + Math.floor(l / 3),
    area: (def.area || 1) * (1 + 0.08 * l),
  };
}
