// Enemy tiers (emoji sprites). `unlockAt` gates a tier into the weighted spawn pool
// over the run; base stats are multiplied by the difficulty curve's scale knobs at
// spawn time. Ogre is an ELITE — spawned on its own timer (not the normal pool) and
// always drops a chest.
export const ENEMIES = {
  wisp: {
    id: "wisp",
    name: "Wisp",
    emoji: "👻",
    size: 24,
    hp: 8,
    speed: 70,
    dmg: 6,
    xp: 2,
    coinChance: 0.06,
    unlockAt: 0,
    weight: 10,
  },
  bat: {
    id: "bat",
    name: "Bat",
    emoji: "🦇",
    size: 22,
    hp: 5,
    speed: 96,
    dmg: 5,
    xp: 2,
    coinChance: 0.06,
    unlockAt: 25,
    weight: 9,
  },
  zombie: {
    id: "zombie",
    name: "Zombie",
    emoji: "🧟",
    size: 28,
    hp: 26,
    speed: 44,
    dmg: 10,
    xp: 4,
    coinChance: 0.08,
    unlockAt: 60,
    weight: 7,
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    emoji: "💀",
    size: 25,
    hp: 16,
    speed: 64,
    dmg: 9,
    xp: 4,
    coinChance: 0.08,
    unlockAt: 110,
    weight: 7,
  },
  spider: {
    id: "spider",
    name: "Spider",
    emoji: "🕷️",
    size: 23,
    hp: 13,
    speed: 108,
    dmg: 8,
    xp: 4,
    coinChance: 0.08,
    unlockAt: 175,
    weight: 6,
  },
  specter: {
    id: "specter",
    name: "Specter",
    emoji: "👺",
    size: 22,
    hp: 18,
    speed: 138,
    dmg: 11,
    xp: 6,
    coinChance: 0.1,
    unlockAt: 240,
    weight: 5,
  },
  ogre: {
    id: "ogre",
    name: "Ogre",
    emoji: "👹",
    size: 44,
    hp: 240,
    speed: 40,
    dmg: 18,
    xp: 30,
    coinChance: 1,
    elite: true,
    dropsChest: true,
    unlockAt: 80,
  },
  lich: {
    id: "lich",
    name: "Lich",
    emoji: "🧟‍♂️",
    size: 38,
    hp: 460,
    speed: 54,
    dmg: 22,
    xp: 55,
    coinChance: 1,
    elite: true,
    dropsChest: true,
    unlockAt: 150,
  },

  // ── Easter-egg variants (special: true keeps them out of both spawn pools;
  //    the spawner rolls them explicitly) ──
  disco: {
    id: "disco",
    name: "Disco Wisp",
    emoji: "🪩",
    size: 26,
    hp: 30,
    speed: 95,
    dmg: 0, // harmless — it just wants to dance
    xp: 5,
    coinChance: 0,
    coinBurst: 5,
    flees: true,
    special: true,
    unlockAt: 0,
  },
  karen: {
    id: "karen",
    name: "Karen",
    emoji: "🧟‍♀️",
    size: 30,
    hp: 40,
    speed: 124, // 2x zombie
    dmg: 10,
    xp: 12,
    coinChance: 0,
    coinBurst: 3,
    special: true,
    unlockAt: 60,
  },
};

export const ENEMY_IDS = Object.keys(ENEMIES);
// Normal (non-elite, non-special) tiers, used by the weighted spawn pool.
export const NORMAL_TIERS = ENEMY_IDS.filter(
  (id) => !ENEMIES[id].elite && !ENEMIES[id].special,
);
// Elites spawn on their own staggered timers (not the weighted pool).
export const ELITE_IDS = ENEMY_IDS.filter((id) => ENEMIES[id].elite);
